In [1]:
import pandas as pd

In [2]:
df_support = pd.read_csv('data/splits/6C_support.csv').sample(frac = 1)
df_support_augmented = pd.read_csv('data/splits/6C_support_augmented.csv').sample(frac = 1)

In [3]:
df_support

,Patient,lame,patch,classe,tetraClass,label,dataset
9468,231,TL,TL_231_A (14).jpg,Tissu lymphoïde,TL,3,train
6566,7,R,R_7_A (33).jpg,Réactionnel,P,0,train
3483,3,No,No_3_C(246).jpg,Normal,P,0,train
1765,7,R,R_7_A (690).jpg,Réactionnel,P,0,train
4054,231,R,R_231_A (234).jpg,Réactionnel,P,0,train
...,...,...,...,...,...,...,...
617,7,R,R_7_A (3724).jpg,Réactionnel,P,0,train
6059,398,R,R_398_A (404).jpg,Réactionnel,P,0,train
11097,231,F,F_231_A (515).jpg,Fibrose,Fi,4,train
16972,169,Fo,Fo_169_A (51).jpg,Foetal,T,5,train
11149,9,F,F_9_S (548).tif,Fibrose,Fi,4,train

In [4]:
df_support_augmented

,Patient,lame,patch,classe,tetraClass,label,dataset
52900,7,A,A_7_A (13).jpg,Acinaire,T,5,train
57139,231,S,S_231_A (624)_VF.jpg,Solide,T,5,train
27397,9,N,N_9_S (193)_rot45.jpg,Nécrose,Né,2,train
1606,7,R,R_7_A (3255)_VF.jpg,Réactionnel,P,0,train
70794,72,Gc,Gc_72_B (245).jpg,Glandulaire complexe,T,5,train
...,...,...,...,...,...,...,...
59699,133,A,133_A_row_370_col_237_VF.jpg,Lépidique,T,5,train
47103,9,F,F_9_S (821)_VF.jpg,Fibrose,Fi,4,train
22705,398,R,R_398_A (1544)_HF.jpg,Réactionnel,P,0,train
7444,72,No,No_72_B (24)_VF.jpg,Normal,P,0,train
40124,231,F,F_231_A (51)_rot135.jpg,Fibrose,Fi,4,train

In [7]:
# delete from df_support_augmented the rows that are in df_support
df_support_only_augmented = df_support_augmented[~df_support_augmented['patch'].isin(df_support['patch'])]
df_support_only_augmented

,Patient,lame,patch,classe,tetraClass,label,dataset
57139,231,S,S_231_A (624)_VF.jpg,Solide,T,5,train
27397,9,N,N_9_S (193)_rot45.jpg,Nécrose,Né,2,train
1606,7,R,R_7_A (3255)_VF.jpg,Réactionnel,P,0,train
65766,72,Gc,Gc_72_B (277)_HF.jpg,Glandulaire complexe,T,5,train
42582,9,F,F_9_S (865)_rot45.jpg,Fibrose,Fi,4,train
...,...,...,...,...,...,...,...
59699,133,A,133_A_row_370_col_237_VF.jpg,Lépidique,T,5,train
47103,9,F,F_9_S (821)_VF.jpg,Fibrose,Fi,4,train
22705,398,R,R_398_A (1544)_HF.jpg,Réactionnel,P,0,train
7444,72,No,No_72_B (24)_VF.jpg,Normal,P,0,train
40124,231,F,F_231_A (51)_rot135.jpg,Fibrose,Fi,4,train

In [8]:
# save the new df_support_augmented
df_support_only_augmented.to_csv('data/splits/6C_support_only_augmented.csv', index=False)